debian/control, debian/maratona-conflitos.postinst, debian/maratona-conflitos.postrm
O maratona-conflitos elimina os pacotes não necessários ao competidor do
maratona no Ubuntu 18.04. São eles pacotes de e-mail, bluetooth, ferramentas
de escritório (pacote do libreoffice), jogos, torrent e alguns pacotes do
gnome.
debian/maratona-meta.post{inst,rm}: Adaptação do login de usuário,
que antes, nas versões anteriores do Ubuntu utilizava o Lightdm agora
utiliza-se o GDM.
Segue a lista dos pacotes adicionados aos conflitos:
aisleriot, gnome-mahjongg, gnome-mines, gnome-sudoku, libgnome-games-support,
libgnome-games-support-common, rhythmbox, nautilus-sendto, bluez,
gnome-bluetooth, pulseaudio-module-bluetooth, bluez-cups, bluez-obexd,
cheese, cups, mythes-en-us, uno-libs3, transmission-gtk, shotwell,
ubuntu-web-launchers.
=> debian/control: Atualizado os conflitos para Ubuntu 18.04.

debian/control, debian/maratona-linguagens.postinst, debian/maratona-linguagens.templates
debian/control: Atualizado as dependências libstdc++6-4.7-dev para
libstdc++-7-dev e libstdc++6-4-7-dbg para libstdc++6-7-dgb. Removendo o fpc como
dependência.
debian/maratona-linguagens.postinst: Script de instalação para o Kotlin, da
Jetbrains, pelo repositório do Snap. Juntamente com a instalação, foi adicionado
uma verificação de erro, para casos de falha na instalação, o usuário poder
decidir fazer uma nova tentativa na instalação do mesmo ou tentar instalar
depois com dpkg-reconfigure maratona-linguagens.
debian/maratona-linguagens.templates: Adicionado os templates necessários para
perguntar ao usuário, em caso de falhas nas instalações dos programas via
snap, se ele deseja tentar novamente fazer a instalação do programa ou se deseja
fazer outra hora.
Signed-off-by: Wall Berg …
=> debian/{control,maratona-linguagens.*}: Atualizando dependências e scripts

debian/control, debian/rules, icones-desktop/cppannotations.desktop, icones-desktop/javadoc.desktop, icones-desktop/python3doc.desktop, icones-desktop/stldoc.desktop
debian/control: Atualizando a libstdc++6-4.7-doc para libstdc++-7-doc e
removendo das dependência o c++-annotations, stl-manual e o fpc-docs-3.0.0.
debian/rules: Agora o maratona-linguagens-doc cria atalhos no
/usr/share/applications.
icones-desktop/: Removido os atalhos cppannotations.desktop e stldoc.desktop.
=> debian/{control, rules}: Atualizando dependências do maratona-linguagens-doc

debian/control, debian/maratona-skel.postinst, debian/rules
debian/control: Todos os pacotes que antes tinha como dependência o
maratona-skel, passam conflitar com ele.
maratona-skel não é mais necessário para o maratona-linux, pois sua função será
agora exercida pelo o maratona-desktop.
=> debian/{control,maratona-skel*,rules}: Removendo maratona-skel do maratona-meta

debian/control, debian/maratona-usuario-icpc.postinst, scripts-administrativos/zera-home-icpc
debian/control: Agora o maratona-usuario-icpc copia os atalhos do
maratona-linguagens-doc para a área de trabalho. Então, por consequência, agora
o maratona-usuario-icpc pré-depende do maratona-linguagens-doc.
debian/maratona-usuario-icpc.postinst: Agora este script copia os atalhos
referentes do maratona-linguagens-doc para a área de trabalho.
scripts-administrativos/zera-home-icpc: Agora este script copia os atalhos
referentes do maratona-linguagens-doc para a área de trabalho para garantir
que quando a home do usuário for zerada, os atalhos das documentações
estejam no seu devido lugar.
=> debian/{control, maratona-usuario-icpc*}: Atualizando dependências e scripts.

debian/maratona-desktop.postinst, debian/rules
debian/maratona-desktop.postinst: Script que tem como função inserir os editores
utilizados pelo usuário do maratona na barra de favoritos. Os atalhos que foram
inseridos são: firefox_boca, eclipse, gedit, geany, emacs25, kate,
codeblocks, gnome-terminal, pycharm-community, intellij-idea-community e
netbeans.
debian/rules: O icone do firefox é copiado para /usr/share/applications/
com o nome de firefox_boca, este atalho faz com que o firefox abra na página
do BOCA.
=> debian/{control,rules,maratona-desktop*}: Atualização de conflitos e scripts.

debian/maratona-usuario-icpc.postinst
debian/maratona-usuario-icpc.postinst: No script de postinst do
maratona-usuario-icpc foi removido a mensagem de primeiro acesso do gnome. Pois
como será feita uma constante limpeza na home do usuário icpc, para não aparecer a
mensagem de primeiro acesso foi preciso colocar um arquivo chamado
gnome-initial-setup-done dentro da pasta /etc/skel/.config/.
Esse arquivo é o mesmo que é criado pelo o gnome quando a mensagem
aparece no primeiro acesso do usuário, então a solução é simular
que a mensagem já apareceu criando o arquivo.
=> debian/maratona-usuario-icpc.postinst: Tirada mensagem de primeiro acesso do Gnome

debian/maratona-usuario-icpc.postinst, debian/rules, usuario-icpc-service/maratona-usuario-icpc.service
debian/rules: Foi adicionado no pacote do maratona-usuario-icpc um arquivo
.service que é reconhecido pelo systemd. Este arquivo possui o nome de
maratona-usuario-icpc.service, na qual esse arquivo fica na pasta
/lib/systemd/system/.
usuario-icpc-service/maratona-usuario-icpc.service: Arquivo nos padrões do
systemd que executa o script zera-home-icpc ao inicializar o sistema. Esse
script sempre falha caso não existir o arquivo criado pelo o
clean-icpc-on-reboot, caso contrario, ele é executado com sucesso. Removido
trecho do Script que fazia essa função pelo /etc/rc.local
debian/maratona-usuario-icpc.postinst: No script de postinst o serviço é
habilitado pelo systemctl.
=> maratona-usuario-icpc: zera-home-icpc agora é executado ao inicializar o sistema.

debian/control
debian/control: Adicionado como dependencia ao maratona-editores o
python3-distutils e python-distutils-extra como correção da mensagem de erro
gerada pelo Pycharm na primeira inicializao de projeto, no qual reclamava  da falta 
do python-distutils. Portanto, instalando esse pacote juntamente com o 
maratona-editores, resolve o problema.
=> maratona-editores: Correção de bugs.

debian/control
Como as IDEs instaladas no maratona-editores só funcionam com os devidos
compiladores instalados, então para que não ocorra problemas, foi adicionado o
maratona-linguagens como pré-dependencia deste pacote.
=> maratona-editores: pré-depende do maratona-linguagens.

debian/control
debian/control: Netbeans removido como dependência do maratona-editores por
causa de incompatibilidade com a versão do openjdk-default
=> maratona-editores: Removido o netbeans como dependência.

debian/maratona-usuario-icpc.postinst
debian/maratona-usuario-icpc.postinst: O mesmo arquivo que o
clean-icpc-on-reboot cria na home do icpc é criado ao final da instalação do
maratona-usuario-icpc a fim de que no reboot, o script do zera-home-icpc seja
executado com sucesso. Garantindo, assim, que a home do usuário icpc seja
limpa no primeiro reboot. É feita também uma "limpeza" neste script a
fim de eliminar partes repetidas no script em relação ao zera-home-icpc. Essas
eliminações foram feitas no trecho que é feita a copia dos icones das
documentações presentes na /usr/share/applications/ para o /home/icpc/Deskto
para o /home/icpc/Desktop/.
=> maratona-usuario-icpc: Arquivo .clean-home adicioanado na home do usuario icpc.

debian/rules, scripts-administrativos/zera-home-icpc
debian/rules: Adicionando em /etc/skel o arquivo
maratona-desktop-configs.tar.xz com objetivo de copiar todas as configurações
dos editores da jetbrains que possui como primeira tela, um termo de aceite, que
não pode ser exibido para o usuário. O arquivo é embarcado dentro do pacote do
maratona-editores.
scripts-administrativos/zera-home-icpc: Adicionado um trecho do script no qual o
arquivo maratona-dekstop-configs.tar.xz que foi copiado para home do usuário
icpc é extraído e excluído, a fim de que o usuário não tenha consigo esse
arquivo em sua home.
maratona-editores-config/maratona-desktop-configs.tar.xz: Arquivo com todas as
configurações iniciais necessárias dos programas da jetbrains e do eclipse. Com
esses arquivos na home do usuário, no primeiro acesso apos zerar a home do …
=> maratona-{editores,usuario-icpc}: Adicionado arquivo de configuração dos editores

debian/maratona-usuario-icpc.postinst
debian/maratona-usuario-icpc.postinst: Senha mudada para "icpcd" a fim de forçar
o usuário reiniciar a máquina após a instalação do usuário icpc. Esse
procedimento é realizado a fim de que os scripts de restauração do usuario icpc
é feito juntamente com o boot do sistema. Quando o usuário é restaurado, é restaurado 
também a senha do usuário como "icpc".
=> maratona-usuario-icpc: Senha invalida para o primeiro acesso do usuário icpc.

debian/maratona-usuario-icpc.postinst, scripts-administrativos/zera-home-icpc
debian/maratona-usuario-icpc.postinst: Agora é responsabilidade do script
zera-home-icpc criar o usuário icpc caso ele não existir. Isso facilita quando o
maratona-linux for distruido em imagens onde o usuário icpc não é criado por
padrão. O postinst do maratona-usuario-icpc ele é responsavél por verificar se
existe um usuario icpc na máquina, caso o usuário icpc existir e possuir privilégio de
superusuário, o script é encerrado com retorno de erro. Caso não possuir
privilégio de superusuário, a sua conta de usuário é alterada no sistema.
scripts-administrativos/zera-home-icpc: Agora é responsabilidade desse script
criar o usuário icpc caso ele não exista na máquina. Isso será util quando
estiver disponível a imagem do sistema do maratona-linux. Quando é verificado
que o usuário não …
=> maratona-usuario-icpc: Atualizado scripts de adição de usuario icpc.

maratona-profile/maratona-desktop-profile.sh
Tirando verificação se o arquivo desktop-trusted foi criado na pasta
~/.config/ para que o script funcione com sucesso na imagem que
sera gerada do maratona-linux. Como é um script que executa para poucos
arquivos, somente os atalhos na área de trabalho, sua execução tem pouca
influência na inicialização da sessão de usuário.
=> maratona-profile/maratona-desktop-profile.sh: Tirando verificação de arquivo.

.gitignore, dconf/40-accessibility, scripts-administrativos/zera-home-icpc
The `.gitignore` was updated in order to keep all build artifacts
ignore by Git. Also, the default configuration for new users has
changed in order to enable the accessibility menu and remove Ubuntu's
initial setup dialogue.
- adds build artifacts from `maratona-flatpak` common and
`maratona-task-data` to `.gitignore`
- enables the display of the accessibility menu by default
- removes the initial setup dialogue shown to new users on Ubuntu 20.04
=> Change accessibility and initial setup

debian/changelog
Add all changes made since the last commit which altered the changelog
(514f2c94). This new version has also transitioned to Ubuntu 20.04
(focal)
- Updates `debian/changelog` for version 20210517
=> Update changelog for version 20210517

dconf/50-favorites, debian/changelog, maratona-editores-config/flatpak-consent.tar.xz, maratona-editores-config/jetbrains-prefs.tar.xz
Adds all fixes since commit dbfbcb4: default keyboard is now us, with
options to change for Brazilian and Spanish; home cleaning scripts have
been improved, and configuration files have been updated.
- dconf/80-keyboards: Add `latam` layout and set `us` as default 
- zera-home-icpc: Runs if there is no /home/icpc
- zera-home-icpc: Creates a random password for ICPC when cleaning    
- Remove eclipse from favourites
- Compress uncompressed files
- Update configuration files for 20210517
=> Release version 20210517.1

debian/changelog, debian/control, debian/copyright, debian/maratona-conflitos.postinst, debian/maratona-conflitos.postrm, debian/maratona-desktop-latam.postrm, debian/maratona-desktop-latam.preinst, debian/maratona-usuario-icpc.postinst
* Update maintainer, dependencies and descriptions
- updates maintainer's name and email
- adds VCS information
- adds firefox as a dependency from maratona-desktop
- updates the descriptions of maratona-conflitos, maratona-task-data and 
maratona-flatpak-common (fixes Lintian warning
extended-description-contains-empty-paragraph, check issue #50)
- adds maratona-desktop as a dependency from maratona-desktop-latam
* Set exit on failure for postinst and postrm
- adds set -e for post installation and removal scripts in order to fix 
Lintian maintainer-script-ignores-errors, check issue #50)
- modify maratona-usuario-icpc.postinst to eliminate indirect status
checks that would cause an abnormal execution
* Update machine-readable copyright file
- updates licenses in `debian/copyright`
=> Release version 20210517.2

debian/changelog, flatpak-common-script/install_flatpak.sh, maratona-editores-config/flatpak-consent.tar.xz, maratona-editores-config/jetbrains-prefs.tar.xz, scripts-administrativos/zera-home-icpc
* Fix the installation of VSCode extensions
- pre-package the extensions instead of downloading them at the
installation
- drop Visual Studio Code Java extensions
* Enable specifying the package's version
- update the helper script to enforce a specific version of a flatpak to
be installed
* Update the Jetbrains IDE's preferences
=> Release 20210517.3

debian/changelog, debian/control
* Force conflict with `snapd`
* force the removal of snapd when installing maratona-conflitos
* update description documenting the need of purging the snapd package in
order to fully remove it form the system
=> Release 20210517.4
